// Response for v1/me/player/currently-playing
export const mockCurrentlyPlaying = {
  device: {
    id: "b1c7d8c8a14e3e8e5b7c8d9f7a6b5c4a",
    is_active: true,
    is_private_session: false,
    is_restricted: false,
    name: "MacBook Pro",
    type: "computer",
    volume_percent: 75,
    supports_volume: true,
  },
  repeat_state: "off",
  shuffle_state: false,
  context: {
    type: "album",
    href: "https://api.spotify.com/v1/albums/3v6dR6bJzY1vX3WgZQp6b8",
    external_urls: {
      spotify: "https://open.spotify.com/album/3v6dR6bJzY1vX3WgZQp6b8",
    },
    uri: "spotify:album:3v6dR6bJzY1vX3WgZQp6b8",
  },
  timestamp: 1625247600000,
  progress_ms: 45213,
  is_playing: false,
  item: {
    album: {
      album_type: "album",
      total_tracks: 13,
      available_markets: ["US", "GB", "DE", "FR", "SE"],
      external_urls: {
        spotify: "https://open.spotify.com/album/3v6dR6bJzY1vX3WgZQp6b8",
      },
      href: "https://api.spotify.com/v1/albums/3v6dR6bJzY1vX3WgZQp6b8",
      id: "3v6dR6bJzY1vX3WgZQp6b8",
      images: [
        {
          url: "https://i.scdn.co/image/ab67616d0000b2738b32b139981e79f2ebe005eb",
          height: 640,
          width: 640,
        },
        {
          url: "https://i.scdn.co/image/ab67616d0000b2738b32b139981e79f2ebe005eb",
          height: 300,
          width: 300,
        },
        {
          url: "https://i.scdn.co/image/ab67616d0000b2738b32b139981e79f2ebe005eb",
          height: 64,
          width: 64,
        },
      ],
      name: "Oracular Spectacular",
      release_date: "2007-10-02",
      release_date_precision: "day",
      restrictions: {},
      type: "album",
      uri: "spotify:album:3v6dR6bJzY1vX3WgZQp6b8",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/0SwO7SWeDHJijQ3XNS7xEE",
          },
          href: "https://api.spotify.com/v1/artists/0SwO7SWeDHJijQ3XNS7xEE",
          id: "0SwO7SWeDHJijQ3XNS7xEE",
          name: "MGMT",
          type: "artist",
          uri: "spotify:artist:0SwO7SWeDHJijQ3XNS7xEE",
        },
      ],
    },
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/0SwO7SWeDHJijQ3XNS7xEE",
        },
        href: "https://api.spotify.com/v1/artists/0SwO7SWeDHJijQ3XNS7xEE",
        id: "0SwO7SWeDHJijQ3XNS7xEE",
        name: "MGMT",
        type: "artist",
        uri: "spotify:artist:0SwO7SWeDHJijQ3XNS7xEE",
      },
    ],
    available_markets: ["US", "GB", "DE", "FR", "SE"],
    disc_number: 1,
    duration_ms: 302693,
    explicit: false,
    external_ids: {
      isrc: "USSM10702155",
      ean: "",
      upc: "",
    },
    external_urls: {
      spotify: "https://open.spotify.com/track/6Qyc6fS4DsZjB2mRW9DsQs",
    },
    href: "https://api.spotify.com/v1/tracks/6Qyc6fS4DsZjB2mRW9DsQs",
    id: "6Qyc6fS4DsZjB2mRW9DsQs",
    is_playable: true,
    linked_from: {},
    restrictions: {},
    name: "Kids",
    popularity: 78,
    preview_url:
      "https://p.scdn.co/mp3-preview/6b1c7d8c8a14e3e8e5b7c8d9f7a6b5c4a1b2c3d4?cid=774b29d4f13844c495f206cafdad9c86",
    track_number: 8,
    type: "track",
    uri: "spotify:track:6Qyc6fS4DsZjB2mRW9DsQs",
    is_local: false,
  },
  currently_playing_type: "track",
  actions: {
    interrupting_playback: false,
    pausing: true,
    resuming: true,
    seeking: true,
    skipping_next: true,
    skipping_prev: true,
    toggling_repeat_context: true,
    toggling_shuffle: true,
    toggling_repeat_track: true,
    transferring_playback: true,
  },
};

// Response for /v1/me/player
export const mockPlayerState = {
  device: {
    id: "b1c7d8c8a14e3e8e5b7c8d9f7a6b5c4a",
    is_active: true,
    is_private_session: false,
    is_restricted: false,
    name: "MacBook Pro",
    type: "computer",
    volume_percent: 75,
    supports_volume: true,
  },
  repeat_state: "off",
  shuffle_state: false,
  context: {
    type: "album",
    href: "https://api.spotify.com/v1/albums/3v6dR6bJzY1vX3WgZQp6b8",
    external_urls: {
      spotify: "https://open.spotify.com/album/3v6dR6bJzY1vX3WgZQp6b8",
    },
    uri: "spotify:album:3v6dR6bJzY1vX3WgZQp6b8",
  },
  timestamp: 1625247600000,
  progress_ms: 45213,
  is_playing: false,
  item: {
    album: {
      album_type: "album",
      total_tracks: 13,
      available_markets: ["US", "GB", "DE", "FR", "SE"],
      external_urls: {
        spotify: "https://open.spotify.com/album/3v6dR6bJzY1vX3WgZQp6b8",
      },
      href: "https://api.spotify.com/v1/albums/3v6dR6bJzY1vX3WgZQp6b8",
      id: "3v6dR6bJzY1vX3WgZQp6b8",
      images: [
        {
          url: "https://i.scdn.co/image/ab67616d0000b2738b32b139981e79f2ebe005eb",
          height: 640,
          width: 640,
        },
        {
          url: "https://i.scdn.co/image/ab67616d0000b2738b32b139981e79f2ebe005eb",
          height: 300,
          width: 300,
        },
        {
          url: "https://i.scdn.co/image/ab67616d0000b2738b32b139981e79f2ebe005eb",
          height: 64,
          width: 64,
        },
      ],
      name: "Oracular Spectacular",
      release_date: "2007-10-02",
      release_date_precision: "day",
      restrictions: {},
      type: "album",
      uri: "spotify:album:3v6dR6bJzY1vX3WgZQp6b8",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/0SwO7SWeDHJijQ3XNS7xEE",
          },
          href: "https://api.spotify.com/v1/artists/0SwO7SWeDHJijQ3XNS7xEE",
          id: "0SwO7SWeDHJijQ3XNS7xEE",
          name: "MGMT",
          type: "artist",
          uri: "spotify:artist:0SwO7SWeDHJijQ3XNS7xEE",
        },
      ],
    },
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/0SwO7SWeDHJijQ3XNS7xEE",
        },
        href: "https://api.spotify.com/v1/artists/0SwO7SWeDHJijQ3XNS7xEE",
        id: "0SwO7SWeDHJijQ3XNS7xEE",
        name: "MGMT",
        type: "artist",
        uri: "spotify:artist:0SwO7SWeDHJijQ3XNS7xEE",
      },
    ],
    available_markets: ["US", "GB", "DE", "FR", "SE"],
    disc_number: 1,
    duration_ms: 302693,
    explicit: false,
    external_ids: {
      isrc: "USSM10702155",
      ean: "",
      upc: "",
    },
    external_urls: {
      spotify: "https://open.spotify.com/track/6Qyc6fS4DsZjB2mRW9DsQs",
    },
    href: "https://api.spotify.com/v1/tracks/6Qyc6fS4DsZjB2mRW9DsQs",
    id: "6Qyc6fS4DsZjB2mRW9DsQs",
    is_playable: true,
    linked_from: {},
    restrictions: {},
    name: "Kids",
    popularity: 78,
    preview_url:
      "https://p.scdn.co/mp3-preview/6b1c7d8c8a14e3e8e5b7c8d9f7a6b5c4a1b2c3d4?cid=774b29d4f13844c495f206cafdad9c86",
    track_number: 8,
    type: "track",
    uri: "spotify:track:6Qyc6fS4DsZjB2mRW9DsQs",
    is_local: false,
  },
  currently_playing_type: "track",
  actions: {
    interrupting_playback: false,
    pausing: true,
    resuming: true,
    seeking: true,
    skipping_next: true,
    skipping_prev: true,
    toggling_repeat_context: true,
    toggling_shuffle: true,
    toggling_repeat_track: true,
    transferring_playback: true,
  },
};
